Update falco-m1.md, use modern-bpf for helm
Using modern-bpf instead of bpf resolves the issue like this:

Error: BPF probe is compiled for 5.15.0-100-generic-64k, but running version is 5.15.0-100-generic

Signed-off-by: Dmitry S. Vlasov <z1nkum@gmail.com>